apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels: 
        app: postgresdb
    spec:
      containers:
        - name: show-me-the-code
          image: postgres
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_DB
              value: show-me-the-code
            - name: POSTGRES_USER
              value: postgresuser
            - name: POSTGRES_PASSWORD
              value: postgrespwd

---

apiVersion: v1
kind: Service
metadata:
  name: postgresdb  
spec:
  selector: 
    app: postgresdb
  ports:
  - port: 5432

